# Dumps the travel_to_anchors table to db/travel_to_anchors_seeds.rb so cached anchor→property
# times survive a DB reset without re-hitting the Routes API. Shared by:
#   • `rake travel_to_anchors:generate_seed` (manual, full dump)
#   • AnchorTravelTimesService, which calls this right after caching a not-seen-before anchor's
#     times — so a first-time anchor (e.g. a user's map pin) is captured automatically.
#
# Anchors are referenced by a stable natural key (class + name for Place/Neighborhood, rounded
# lat/lng for CustomAnchor) and properties by name, so the seed restores correctly on any DB even
# when auto-increment ids differ. The dump is a full snapshot (not an append), so it can never
# drift out of sync with the table.
class TravelToAnchorsSeedWriter
  SEED_PATH = Rails.root.join("db/travel_to_anchors_seeds.rb")

  def self.call(path: SEED_PATH)
    new(path).call
  end

  def initialize(path)
    @path = path
  end

  def call
    File.open(@path, "w") do |file|
      file.puts(HEADER)
      TravelToAnchor.includes(:anchor, :property).find_each do |row|
        line = entry_line(row)
        file.puts(line) if line
      end
      file.puts("]")
      file.puts(LOADER)
    end
    @path
  end

  private

  def entry_line(row)
    anchor = row.anchor
    property = row.property
    return nil unless anchor && property

    ref =
      if anchor.is_a?(CustomAnchor)
        { type: "CustomAnchor", lat: anchor.latitude&.round(4), lng: anchor.longitude&.round(4), label: anchor.label }
      else
        { type: anchor.class.name, name: anchor.name }
      end

    "  { anchor: #{ref.inspect}, property_name: #{property.name.inspect}, travel_time: #{row.travel_time.inspect} },"
  end

  HEADER = <<~'RUBY'
    # Generated by TravelToAnchorsSeedWriter — `rake travel_to_anchors:generate_seed`, and
    # automatically after AnchorTravelTimesService caches a new anchor. Do not edit by hand.
    #
    # Persists cached anchor→property travel times so they survive a DB reset without re-hitting
    # the Routes API. Anchors are referenced by a stable natural key (class + name for Place/
    # Neighborhood, rounded lat/lng for CustomAnchor) and properties by name, so ids may differ on
    # a fresh DB and the seed still restores correctly.
    #
    # Idempotent: find_or_create_by on the unique (anchor, property) pair never duplicates.

    TRAVEL_TO_ANCHORS_SEED = [
  RUBY

  LOADER = <<~'RUBY'

    TRAVEL_TO_ANCHORS_SEED.each do |entry|
      ref = entry[:anchor]
      anchor =
        case ref[:type]
        when "CustomAnchor"
          CustomAnchor.find_or_create_by(latitude: ref[:lat], longitude: ref[:lng]) { |a| a.label = ref[:label] }
        when "Neighborhood"
          Neighborhood.find_by(name: ref[:name])
        when "Place"
          Place.find_by(name: ref[:name])
        end
      property = Property.find_by(name: entry[:property_name])
      next unless anchor && property

      TravelToAnchor.find_or_create_by(anchor: anchor, property: property) do |t|
        t.travel_time = entry[:travel_time]
      end
    end
  RUBY
end
