namespace :places do
  desc "Generate db/google_places_seeds_v2.rb from the database (v2 per-property structure). Does not call the API."
  task generate_seed_v2: :environment do
    seed_path = Rails.root.join("db/google_places_seeds_v2.rb")

    File.open(seed_path, "w") do |file|
      file.puts <<~RUBY
        # Generated by `rake places:generate_seed_v2`. Do not edit by hand.
        #
        # Keyed by property name (not id) so this seed works correctly on any DB,
        # including fresh ones where auto-increment ids differ from when data was fetched.
        #
        # WARNING: Running this seed creates new Place rows. To re-seed cleanly:
        #   Place.where.not(property_id: nil).destroy_all
        #   load 'db/google_places_seeds_v2.rb'

        PROPERTY_PLACES_V2 = {
      RUBY

      Property.order(:id).find_each do |property|
        file.puts "  #{property.name.inspect} => {"
        file.puts "    score_inputs: #{property.score_inputs.inspect},"
        file.puts "    places: ["

        property.places.order(:category, :distance_meters).find_each do |place|
          file.puts <<~RUBY.gsub(/^/, "      ")
            {
              category: #{place.category.inspect},
              place_id: #{place.place_id.inspect},
              name: #{place.name.inspect},
              latitude: #{place.latitude},
              longitude: #{place.longitude},
              rating: #{place.rating.inspect},
              distance_meters: #{place.distance_meters.inspect}
            },
          RUBY
        end

        file.puts "    ]"
        file.puts "  },"
      end

      file.puts "}"

      file.puts <<~RUBY

        PROPERTY_PLACES_V2.each do |property_name, payload|
          property = Property.find_by(name: property_name)
          next unless property # skip if property no longer exists

          payload[:places].each do |place_attrs|
            Place.create!(place_attrs.merge(property_id: property.id))
          end

          property.update!(score_inputs: payload[:score_inputs])
        end
      RUBY
    end

    puts "Wrote #{seed_path}"
  end
end
