properties_data = [
  {:name=>"EstLargo Meguro - Studio 302",
  :availability=>"now",
  :neighborhood=>"Meguro",
  :latitude=>35.6311609,
  :longitude=>139.7107435,
  :price=>202000,
  :layout=>"1DK",
  :bedrooms=>1,
  :size=>24,
  :floors=>3,
  :description=>
    "Nestled a few minutes south of Meguro Station, this renovated property is well suited for someone looking to explore the area. Just beyond the city’s inner circle, Meguro District attracts commuters, families, and artists who appreciate subtle charms over sonorous environs. Despite its far-away residential feel, Meguro is not short of things to do. Cafes, famous izakaya, repurposed vintage shops, and must-see bookstores generate buzz that brings this area to life.",
  :rules=>
    "1. Room availability is subject to real-time inventory constraints. Discounted rates apply only to designated room types and quantities.2. All promotional discounts are dynamically calculated based on: (i) booking date, and (ii) geographical location of the property.3. Offer cannot be used in conjunction with any other offer until availability is sold out.4. For details on the promotion terms, conditions, and availability, please contact us.5. Dash Living reserves the right to change the Terms and Conditions, and suspend or terminate the offers at any time without prior notice.6. Images are for illustration only, some of decorations shown might not be included in the actual room.7. Subject to room type and availability. Please contact our specialist for further details.",
  :vendor=>"Dash Living",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/S6TxBMTyBw-1765955575782.jpg",
  :features=>["Elevator", "Free internet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=gZYMM3kiJXe",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/puphRCu2B5-1766996461853.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/SUtju9s1bW-1766996461929.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/AAD7LKX5XA-1766996461971.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/dwknxki-9b-1766996462015.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/MUOT5R4NRK-1766996462053.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/t3Nf46yTLb-1766996462109.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Kos3995cj4-1766996462150.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9YN1vGHfRh-1766996462192.jpg"],
  :stations=>["Meguro Sta. - 8 min walk", "Fudomae Sta. - 8 min walk"]},

  {:name=>"The Parkhabio Meguro Place 2",
  :availability=>"June 15th",
  :neighborhood=>"Meguro",
  :latitude=>35.6334663,
  :longitude=>139.712204,
  :price=>232000,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>34,
  :floors=>6,
  :description=>
    "Discover the best of Tokyo, with this one bedroom apartment in Shimomeguro. It’ll be easy to simply show up and start living in this beautifully Blueground furnished apartment with its fully equipped kitchen, bright living room, and our dedicated, on-the-ground support. (ID #TYO180)Rates vary depending on the duration of stay, season, and other parameters. For exact pricing, please visit our website and enter your desired move-in and move-out dates.• Gorgeous furniture• Fully equipped kitchen• Smart TV• Premium wireless speaker• Ideally located in Tokyo• Superior quality mattresses in every bedroom• Luxury linens and cozy towelsSleeping arrangementsDouble Bed, 55in/140cmAmenitiesBuilding amenities unique to this one bedroom apartment include an on-site:ElevatorWashing machine",
  :rules=>
    "・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Bath & WS separated", "Delivery box", "Elevator"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=gEnYRit6gTb",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/gnmfMHCDUa-1763646165327.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Geb8TvJhIG-1763646166193.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aOtzl1UtYx-1763646165432.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/7X6z2G-iZf-1763646165478.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/v6uIq30gq3-1763646165529.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/j2HAFd6jUk-1763646165573.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/3Sq-qJ9mXG-1763646165618.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/utSsKBJA2v-1763646165673.png"],
  :stations=>["Meguro Sta. - 5 min walk"]},

  {:name=>"Hmlet Nishi 405",
  :availability=>"August 9th",
  :neighborhood=>"Shibuya",
  :latitude=>35.6563239,
  :longitude=>139.704141,
  :price=>292110,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>33,
  :floors=>4,
  :description=>
    "【Fresh Start Special Discount】 Get ¥20,000 OFF your move-in costs!Kickstart your new life with Hmlet! We are excited to offer a special discount to help you settle in.Why not take this opportunity to experience the Hmlet lifestyle? A stylish living space and a convenient, comfortable lifestyle are waiting for you.＜Campaign Details＞Offer: ¥20,000 OFF your initial move-in costs＜Terms & Conditions＞Move-in Period: Applicable for residents starting their stay between May 1 and June 30, 2026Eligible Properties: All Hmlet propertiesEligibility: This campaign is available exclusively to first-time residents who sign a new lease. Please note that current residents who are extending their existing contracts, as well as former residents returning through a re-contract or relocating/transferring between Hmlet properties, are not eligible for this discount.＜How to Apply＞When applying, please mention that you saw the campaign.Located just a 4-minute walk from Nishi-shinjuku-gochome Station on the Toei Oedo Line, and a convenient 10-minute stroll to Nakano-sakaue Station on the Tokyo Metro Marunouchi Line, Hmlet Nishi-Shinjuku offers unmatched accessibility in the heart of Tokyo. With a quick 4-minute direct connection to Shinjuku Station, it ensures you have everything you need for daily living right at your fingertips, eliminating any shopping concerns. While Shinjuku's main streets buzz with office buildings and vibrant activity, Nishi-shinjuku offers a tranquil retreat just off the beaten path, providing a peaceful atmosphere amidst the city's hustle and bustle.Explore the expansive Shinjuku Chuo Park, located within walking distance, or indulge in the amenities of SHUKNOVA, a facility featuring restaurants and a fitness club. Experience the beauty of nature throughout the seasons, from lush greenery to cherry blossom viewing during springtime, making it a popular destination for tourists from around the world. Why not embrace the convenience and cosmopolitan lifestyle of Hmlet Nishi-Shinjuku? Your urban adventure awaits!",
  :rules=>
    "＊Move-in Fees (One-time Payment, applicable to all contracts.)Service Fee(Non-refundable): 10% of Rent SubtotalMove Out Cleaning Fee: 25% of List Price＊Optional Fees (If Applicable)Pet Fee: ¥110,000 (Non-refundable)Bicycle Parking Registration Fee: ¥3,300 (One-time payment per bicycle)Rental Futon Set: ¥22,000 (One-time payment per set)＊Included in Service Fee:- Utilities & Internet Fees- Customer Support & Emergency Call Center- No Brokerage Fee- No Key Money Required＊Kitchen Essentials Provided:- Cooking utensils and cutlery are included in the room.https://drive.google.com/file/d/1sSyG7K30TXeBjV3xSmGH7E2I8Xqu1zRB/view",
  :vendor=>"Hmlet Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/nQuMexfOpn-1725438035620.jpg",
  :features=>["Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Free internet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=FfgtwARdmJp",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/pYkPqma_5P-1774321148868.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/GESIbsXLTS-1750069392003.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/RaeZ6wBJHF-1774321171084.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/p5V31oWbEa-1774321133150.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/yUejNWxOxr-1774321133388.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/iV-VPYnFR4-1774321133574.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/XPIHyyA-Fx-1774321108968.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lDPFTQRIe5-1774321109193.jpg"],
  :stations=>["Nakano-sakaue Sta. - 10 min walk", "Nishi-shinjuku-gochome Sta. - 4 min walk", "Tochōmae Sta. - 12 min walk"]},

  {:name=>"Palace Studio 207",
  :availability=>"June 10th",
  :neighborhood=>"Meguro",
  :latitude=>35.6414529,
  :longitude=>139.6980773,
  :price=>185400,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>23,
  :floors=>2,
  :description=>"Maximum Number of Users2 PersonBedDouble Bed(1)Age of Building19 Year(s)",
  :rules=>
    "※This property has free wi-fi.※This property has an android monitor instead of a TV.　There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, Amazon Prime, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Delivery box", "Elevator"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/eTJ8e65Kv_-1732266075484.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VHreBPb3g--1732266076446.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/sTz0wpUMLw-1732266076401.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/1Xij6JAQpg-1732266075699.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ruhTOp_SL5-1732266076146.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/q09qM_zPua-1732266077555.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/d5_Ei0z3aW-1732266077850.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/PztYKWsqL--1732266076218.jpg"],
  :stations=>["Shibuya Sta. - 12 min walk", "Ikejiri-Ohashi Sta. - 11 min walk", "Shinsen Sta. - 7 min walk"]},

  {:name=>"The Apartment Hotel Ebisu 1 Large typeA 102",
  :availability=>"July 7th",
  :neighborhood=>"Ebisu",
  :latitude=>35.6492576,
  :longitude=>139.717365,
  :price=>290000,
  :layout=>"1DK",
  :bedrooms=>1,
  :size=>41,
  :floors=>15,
  :description=>
    "Contrasting the glamorous station-side area, Ebisu’s back streets are lined with shops for those with a discerning eye. The area’s bars are another drawcard, with almost too many renowned establishments to choose from.＊Applianceswashing machine,refrigerator,microwave,electric kettle,coffee dripper,IH stove,tableware,cutlery,pot,frying pan,kitchen knife,cutting board＊Amenities bath amenities, towels, toothbrush, hairbrush(Refills during your stay are not available)Double bed x 1.  Please contact us if you would like to bring your child.",
  :rules=>
    "2026-08-20 ~ 2026-10-01 is available2026-12-01 ~ 2027-03-01 is available＊A guarantor company is required.＊Initial fees consist of:・First month's prorated rent (next month’s rent may be included depending on timing)・Initial fee (10% of monthly rent)・Cleaning fee (20% of monthly rent)",
  :vendor=>"The Apartment Hotel",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/QDKWgNZwef-1753255036160.jpg",
  :features=>["Balcony", "Delivery box", "Elevator", "Free internet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://r15601879.theta360.biz/t/3a931ef0-bb02-11f0-b72e-0ad00fde431f-1",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/zg0cyhPK2E-1755239851972.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/hy_gnj7Jw3-1755239852416.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/grrACNjOLS-1755239852054.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/8rWwxluhS_-1755239852093.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/2wGVxOYYjR-1755239852133.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aRHSIns3gD-1755239852172.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/QIY3RpMkG0-1755239852208.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/fiFl9JofSa-1755239852248.jpg"],
  :stations=>["Ebisu Sta. - 10 min walk", "Hiroo Sta. - 8 min walk"]},

  {:name=>"Hmlet Shibuyaohashi 203",
  :availability=>"now",
  :neighborhood=>"Meguro",
  :latitude=>35.6551771,
  :longitude=>139.6889239,
  :price=>186180,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>18,
  :floors=>2,
  :description=>
    "【Fresh Start Special Discount】 Get ¥20,000 OFF your move-in costs!Kickstart your new life with Hmlet! We are excited to offer a special discount to help you settle in.Why not take this opportunity to experience the Hmlet lifestyle? A stylish living space and a convenient, comfortable lifestyle are waiting for you.＜Campaign Details＞Offer: ¥20,000 OFF your initial move-in costs＜Terms & Conditions＞Move-in Period: Applicable for residents starting their stay between May 1 and June 30, 2026Eligible Properties: All Hmlet propertiesEligibility: This campaign is available exclusively to first-time residents who sign a new lease. Please note that current residents who are extending their existing contracts, as well as former residents returning through a re-contract or relocating/transferring between Hmlet properties, are not eligible for this discount.＜How to Apply＞When applying, please mention that you saw the campaign.Hmlet Shibuya Ohashi: The Perfect Balance of Urban Convenience and Natural Serenity Located within walking distance of Shibuya Station, Hmlet Shibuya Ohashi offers a unique blend of city vibrancy and natural tranquility. With excellent accessibility—just an 8-minute walk from Keio Inokashira Line’s Shinsen Station and a 9-minute walk from Tokyu Den-en-toshi Line’s Ikejiri-Ohashi Station—you can reach Shibuya Station in just 2 minutes. Major hubs like Shinjuku and Shinagawa are also just one transfer away. Additionally, a limousine bus from Shibuya Fukuras provides a direct connection to Haneda Airport in approximately 40 minutes. The property is also conveniently located near the University of Tokyo’s Komaba Campus, making it ideal for students. The surrounding area features 24-hour supermarkets such as Maruetsu and Seijo Ishii, ensuring hassle-free daily shopping. Enjoy the seasonal beauty of cherry blossoms along the Meguro River Greenway, relax at Meguro Sky Garden, or explore Setagaya Park and Komabano Park, perfect for outdoor activities like walking and BBQs. The neighborhood is also dotted with charming cafés, specialty restaurants, and boutique shops, offering plenty of options for leisure and entertainment. Experience a lifestyle where urban convenience meets natural tranquility at Hmlet Shibuya Ohashi. Why not start your next chapter here?",
  :rules=>
    "＊Move-in Fees (One-time Payment, applicable to all contracts.)Service Fee(Non-refundable): 10% of Rent SubtotalMove Out Cleaning Fee: 25% of List Price＊Optional Fees (If Applicable)Pet Fee: ¥110,000 (Non-refundable)Bicycle Parking Registration Fee: ¥3,300 (One-time payment per bicycle)Rental Futon Set: ¥22,000 (One-time payment per set)＊Included in Service Fee:- Utilities & Internet Fees- Customer Support & Emergency Call Center- No Brokerage Fee- No Key Money Required＊Kitchen Essentials Provided:- Cooking utensils and cutlery are included in the room.https://drive.google.com/file/d/1sSyG7K30TXeBjV3xSmGH7E2I8Xqu1zRB/view",
  :vendor=>"Hmlet Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/nQuMexfOpn-1725438035620.jpg",
  :features=>["Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Free internet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=rexoCpMXyxV&ts=1",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/zIEMHV949p-1749629748414.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/oKAHV4ZAvv-1749629573689.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/PMZBHhiURc-1749629748512.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/M9Tjseys2_-1749629748546.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/t4W_cYcmPO-1749629748589.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/KA7uN4gRlv-1749629748712.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/qM441kSDsd-1749629748769.jpg"],
  :stations=>["Shinsen Sta. - 8 min walk"]},

  {:name=>"The Apartment Hotel Shibuya 701",
  :availability=>"now",
  :neighborhood=>"Shibuya",
  :latitude=>35.6540092,
  :longitude=>139.6998735,
  :price=>336000,
  :layout=>"Studio",
  :bedrooms=>0,
  :size=>41,
  :floors=>77,
  :description=>
    "Daikanyama is home to high-quality shops and restaurants with a relaxed atmosphere, away from the hustle and bustle of Shibuya. Starting at Daikanyama T-Site, a cultural symbol, Nakameguro and Ebisu are located just a short walk away, making the area perfect for a stroll on a sunny day.＊Applianceswashing machine,refrigerator,microwave,electric kettle,coffee dripper,IH stove,tableware,cutlery,pot,frying pan,kitchen knife,cutting board＊Amenities bath amenities, towels, toothbrush, hairbrush(Refills during your stay are not available)Double bed x 2 　Please contact us if you would like to bring your child.",
  :rules=>
    "2026-07-31~ 2026-09-30 is available2026-12-01 ~ 2027-03-02 is available＊A guarantor company is required.＊Initial fees consist of:・First month's prorated rent (next month’s rent may be included depending on timing)・Initial fee (10% of monthly rent)・Cleaning fee (20% of monthly rent)",
  :vendor=>"The Apartment Hotel",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/QDKWgNZwef-1753255036160.jpg",
  :features=>["Balcony", "Bath & WS separated", "Delivery box", "Elevator", "Free internet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://r15601879.theta360.biz/t/19064d2c-ab42-11f0-b248-0613720b7bf9-1",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Sj4G1U_eFb-1755241574397.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/CWT4UQi6S6-1755242415907.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/uBTLhAaiO7-1755241574550.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ZRv379Nf8q-1755241574477.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lf-YnmSw7u-1755241574510.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/EKKzrFXgeI-1755241574583.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aIQk7LQk3U-1755241574623.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ihB28ahbdU-1755241574659.jpg"],
  :stations=>["Shibuya Sta. - 6 min walk", "Daikanyama Sta. - 12 min walk"]},

  {:name=>"The Parkhabio Cross #1004 2",
  :availability=>"July 1st",
  :neighborhood=>"Meguro",
  :latitude=>35.6534504,
  :longitude=>139.6934806,
  :price=>337000,
  :layout=>"1SLDK",
  :bedrooms=>1,
  :size=>57,
  :floors=>10,
  :description=>
    "Rental fees are subject to Dynamic Pricing. Contact us for more information.Rates vary depending on the duration of stay, season, and other parameters. For exact pricing, please visit our website and enter your desired move-in and move-out dates.Show up and start living from day one in Tokyo with this comfortable one bedroom Blueground apartment. You’ll love coming home to this thoughtfully furnished, beautifully designed, and fully-equipped Shibuya home with stunning balcony views over the city. (ID #TYO8)Designed with you in mindAs with any Blueground apartment, you’ll find a thoughtfully designed space complete with beautiful furniture and a fully-equipped kitchen in this one bedroom property. And, thanks to our superior quality mattresses, luxury linens, and towels, you can relax knowing you’ll always feel comfortably at home. When you’re ready for some fun, you can take in the Tokyo vibes or bring the entertainment to you with the premium wireless speaker or smart TV.Sleeping arrangementsQueen Bed, 63in/160cmAmenitiesBuilding amenities unique to this one bedroom apartment include an on-site:ElevatorWashing machineLoungeBuilding amenities may have an extra cost.This Blueground apartment has flexible lease options, allowing you to book it for one month, a year, or more.We take great pride in ensuring every photo displayed is shot in our own units with our actual furnishings. That said, we regularly refresh our decor and furniture arrangement, which may differ from what’s pictured.",
  :rules=>
    "・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Balcony", "Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=PunYXwWCgkZ",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9VR65mjUli-1748771243462.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9jDOrhhCMy-1748771244854.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Fp6kCBDeCH-1748771243554.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/w3PqpbfRsG-1748771243625.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/uYDO8gNnbV-1748771243710.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/cMzgMEBHkR-1748771243849.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/hCfKYZK604-1748771243967.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/jbGpOyWA9L-1748771244051.png"],
  :stations=>["Shibuya Sta. - 10 min walk"]},

  {:name=>"T.S. Heim 201",
  :neighborhood=>"Ebisu",
  :availability=>"July 27th",
  :latitude=>35.6451241144,
  :longitude=>139.7132500994,
  :price=>168600,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>14,
  :floors=>2,
  :description=>"・Maximum Number of Users：1 Person・Bed：Shingle x 1・Built in: December 1990",
  :rules=>
    "※This property has an android monitor instead of a TV.There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, prime video, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Bath & WS separated", "Free internet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/0bO3oNwiS9-1745209958170.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/TJ2J_QMAsi-1745209958286.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/tnjOQ5471F-1745209968176.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Bsyvho62_F-1745209968248.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/GzWxYUVEP3-1745209968553.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VBLyRoSPpm-1745209969700.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/7cwBe-Xl1X-1745209968082.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/e0-qvfFd14-1745209968636.jpg"],
  :stations=>["Ebisu Sta. - 5 min walk", "Hiroo Sta. - 17 min walk", "Daikanyama Sta. - 15 min walk"]},

  {:name=>"Oak Rest Ebisu 503 503",
  :neighborhood=>"Ebisu",
  :availability=>"now",
  :latitude=>35.6445351,
  :longitude=>139.7210448,
  :price=>185400,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>20,
  :floors=>5,
  :description=>"Maximum Number of Users：2 PersonBed：Double Bed(1)Age of Building：4 Year(s)",
  :rules=>
    "※This propaty has free wi-fi.※This property has an android monitor instead of a TV.　There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, Amazon Prime, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Bath & WS separated"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ynjWrsGB_p-1739868727650.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/98CB0tjk8s-1739868729425.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/r-Oa5VtOSD-1739868727726.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VxQV85zw7Z-1739868727760.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/okJkIjUGXd-1739868727801.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/LqByqUhT3f-1739868727840.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/MKndITS1sV-1739868727892.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/6o4QkvJk4m-1739868727945.jpg"],
  :stations=>["Shirokanedai Sta. - 14 min walk", "Ebisu Sta. - 13 min walk", "Hiroo Sta. - 10 min walk"]},

  {:name=>"Prime Urban Meguro Riverfront 301",
  :neighborhood=>"Meguro",
  :availability=>"now",
  :latitude=>35.637784,
  :longitude=>139.706143,
  :price=>346000,
  :layout=>"2LDK",
  :bedrooms=>2,
  :size=>64,
  :floors=>3,
  :description=>
    "This prime location offers the best of Tokyo living, just steps from the famous cherry blossom-lined Meguro River. You'll have easy access to the trendy shops and cafes of Nakameguro, the sophisticated dining and nightlife of Ebisu, and the major transportation hub of Meguro Station. Despite being surrounded by these vibrant areas, your home is a peaceful oasis tucked away on a quiet street. Enjoy the convenience of multiple train lines for effortless city access, while returning to a serene, tranquil environment. It’s the perfect blend of dynamic city life and peaceful sanctuary.This Blueground apartment has flexible lease options, allowing you to book it for one month, a year, or more.",
  :rules=>"・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>"https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Bath & WS separated", "Delivery box", "Elevator", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=3YLYDjWxsWU",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/QDpTBrHlOc-1757350157723.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/N1t8kaIxE2-1757350158636.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/6QvIqkpeM8-1757350157809.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/pkS7Oa3KRa-1757350157849.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/a7pacWC2vw-1757350157891.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Fod0ae1u0c-1757350157949.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/KY69JxWT5D-1757350158040.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/541RvV_iEF-1757350158079.png"],
    :stations=>["Meguro Sta. - 13 mins walk", "Nakameguro Sta. - 12 mins walk"]},

  {:name=>"The Sanctus 202",
  :neighborhood=>"Ebisu",
  :availability=>"August 20th",
  :latitude=>35.6427405,
  :longitude=>139.7168302,
  :price=>151800,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>12,
  :floors=>2,
  :description=>"・Maximum Number of Users：1 Person・Bed： Single Sofa bed×1・Age of Building： May 2023",
  :rules=>
    "■Towels and LinensPlease note that towels are provided for the number of guests regardless of the number of nights.※Linens and towels will not be changed during your stay.■Free Wi-Fi available※Please note that facilities and equipment are only provided upon initial installation and are not provided additionally.※This property has an android monitor instead of a TV.There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, prime video, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>"https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Bath & WS separated", "Delivery box", "Free internet", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/iVc6zjXQ1Z-1733385995813.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/s7wtNRdPc3-1733385997369.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/IxfoDWWvaV-1733385996958.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/e_CFykGTUf-1733385996199.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/2vMGdNyHdp-1733385997329.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/wA_CBMCcI6-1750744613500.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/qzYSKJlhwl-1733385996765.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/6IY6ajQ0ks-1733385997115.jpg"],
  :stations=>["Shirokanedai Sta. - 13 mins walk", "Ebisu Sta. - 13 mins walk", "Hiroo Sta. - 14 mins walk"]},

  {:name=>"Hmlet YutenjiⅡ 202",
    :neighborhood=>"Meguro",
    :availability=>"now",
    :latitude=>35.6355753,
    :longitude=>139.6936046,
    :price=>264290,
    :layout=>"Studio",
    :bedrooms=>1,
    :size=>29,
    :floors=>2,
    :description=>
      "Hmlet Yutenji II offers effortless access to major city hubs. Born in the serene residential neighborhood of Nakameguro 5-chome, it is located just a 6-minute walk from Yutenji Station on the Tokyu Toyoko Line.Enjoy easy access to the heart of the city with a 6-minute direct ride to Shibuya and just 2 minutes to Nakameguro. Direct through-service via the Fukutoshin Line allows for transfer-free travel to Shinjuku and Ikebukuro, bringing ease and flexibility to your daily commute and weekend outings.The property's greatest appeal lies in its incredibly convenient surroundings. Daily essentials are just steps away, with \"My Basket\" and \"Welcia\" only a 1-minute walk, and large supermarkets like \"Summit Store\" and \"Ozeki\" gathered within a 5-minute radius. With the station-connected \"Etomo Yutenji\" also available, daily shopping is stress-free. Nearby retro shopping streets like \"Yutenji Shopping Street\" and \"Showa-dori\" invite you to explore unique cafes and renowned local shops.The balance between nature and culture is exquisite. Within walking distance, you can find the tranquility of \"Yutenji Temple,\" a Nationally Registered Tangible Cultural Property. A short stroll leads to lush urban oases like \"Setagaya Park\" and the \"Jakuzure River Green Way.\" This intimate residence of just 7 units is fully equipped with \"NURO\" high-speed internet, creating the perfect environment for comfortable remote work.Discover a place where convenience, tranquility, and the sophisticated culture of Meguro resonate together. Why not start a comfortable and enriching new chapter at Hmlet Yutenji II?",
    :rules=>
      "＊Move-in Fees (One-time Payment, applicable to all contracts.)Service Fee(Non-refundable): 10% of Rent SubtotalMove Out Cleaning Fee: 25% of List Price＊Optional Fees (If Applicable)Pet Fee: ¥110,000 (Non-refundable)Bicycle Parking Registration Fee: ¥3,300 (One-time payment per bicycle)Rental Futon Set: ¥22,000 (One-time payment per set)＊Included in Service Fee:- Utilities & Internet Fees- Customer Support & Emergency Call Center- No Brokerage Fee- No Key Money Required＊Kitchen Essentials Provided:- Cooking utensils and cutlery are included in the room.",
    :vendor=>"Hmlet Japan",
    :vendor_image=>"https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/nQuMexfOpn-1725438035620.jpg",
    :features=>["Bath & WS separated", "Delivery box", "Free internet", "Furnished", "Students allowed"],
    :all_amenities=>["Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "Washing machine"],
    :matterport_url=>nil,
    :images=>
      ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/0SUmvS6Wu8-1772071428725.jpg",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/wzgdDbCEZc-1772071185830.png",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/DJ3FQAMS5T-1772071429151.jpg",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/1I4WD0iXUE-1772071429537.jpg",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9_3-WMzxuN-1772071355355.jpg",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/U8UvIPS3ln-1772071355693.jpg",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/6CDjs2NsQx-1772071356055.jpg",
      "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/pVYa7WtJRL-1772071291536.jpg"],
    :stations=>["Yutenji Sta. - 6 mins walk"]},

  {:name=>"Park Lane Shirokane Takanawa 202",
  :neighborhood=>"Shinagawa",
  :availability=>"now",
  :latitude=>35.6400747154,
  :longitude=>139.7329807187,
  :price=>195000,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>25,
  :floors=>2,
  :description=>"・Maximum Number of Users：3 Person・Bed：Double Bed×1、Single sofa bed x 1・Built in: November 2007",
  :rules=>
    "■Towels and LinensPlease note that towels are provided for the number of guests regardless of the number of nights.※Linens and towels will not be changed during your stay.■Free Wi-Fi available※Please note that facilities and equipment are only provided upon initial installation and are not provided additionally.※This property has an android monitor instead of a TV.There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, prime video, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>"https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Balcony", "Bath & WS separated", "Delivery box", "Elevator", "Free internet", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/GhotpZid_j-1750298038594.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/FFSxyeIPwD-1750298041684.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/yUrQxrip8I-1750298038743.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/kXM-xBHwJE-1750298038818.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Wg0ddo2gEb-1750298038853.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/20-z17f8vP-1750298038921.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/atAxK_x0Yj-1750298038994.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VaVCpr-tS6-1750298039037.jpg"],
  :stations=>["Shirokanedai Sta. - 10 mins walk", "Shirokane-takanawa Sta. - 5 mins walk", "Sengakuji Sta. - 13 mins walk"]},

  {:name=>"Hmlet Higashi Gotanda 1201",
  :neighborhood=>"Shinagawa",
  :availability=>"June 10th",
  :latitude=>35.6264101,
  :longitude=>139.7248988,
  :price=>206510,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>24,
  :floors=>12,
  :description=>
    "Hmlet Higashi Gotanda is located a 6-minute walk from Gotanda Station on the JR Yamanote Line.Gotanda Station offers smooth access to major stations such as Shinagawa, Shinjuku, and Shibuya without transfers, and is conveniently served by the Tokyu Ikegami Line and the Toei Asakusa Subway Line in addition to the JR Line. There are also shopping facilities and supermarkets directly connected to the station for your convenience.The 1K room (studio type) has a regular room with the warmth of modern wood, and a remote work room with furniture that supports telecommuting and gives a calm impression with classic colors.",
  :rules=>
    "＊Move-in Fees (One-time Payment, applicable to all contracts.)Service Fee(Non-refundable): 10% of Rent SubtotalMove Out Cleaning Fee: 25% of List Price＊Optional Fees (If Applicable)Pet Fee: ¥110,000 (Non-refundable)Bicycle Parking Registration Fee: ¥3,300 (One-time payment per bicycle)Rental Futon Set: ¥22,000 (One-time payment per set)＊Included in Service Fee:- Utilities & Internet Fees- Customer Support & Emergency Call Center- No Brokerage Fee- No Key Money Required＊Kitchen Essentials Provided:- Cooking utensils and cutlery are included in the room.",
  :vendor=>"Hmlet Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/nQuMexfOpn-1725438035620.jpg",
  :features=>
    ["Balcony",
    "Bath & WS separated",
    "Bicycle parking",
    "Delivery box",
    "Elevator",
    "Free internet",
    "Furnished",
    "Pet allowed",
    "Students allowed"],
  :all_amenities=>
    ["Air conditioner",
    "Hair dryer",
    "Iron",
    "LAN ethernet socket",
    "Microwave",
    "Refrigerator",
    "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=XEZLuBYYVne",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/F-4TcpSiXH-1762322708247.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/-z8SfgEOlT-1762322684202.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/0hv9CJ8LJt-1762322740978.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/QVa54_mDqP-1762322741066.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ngseDXN5ZX-1762322741109.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/50o8FYm7O--1762322741150.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/C13beLdS82-1762322741188.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/DoO_LqaFNS-1762322741228.jpg"],
  :stations=>["Gotanda Sta. - 4 mins walk"]},

  {:name=>"Nishi 412",
  :neighborhood=>"Gotanda/Osaki",
  :availability=>"now",
  :latitude=>35.628587,
  :longitude=>139.719541,
  :price=>232200,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>25,
  :floors=>4,
  :description=>nil,
  :rules=>
  "※The monthly rent displayed is calculated based on the daily rate multiplied by 30 days. The actual total cost will vary depending on the length of your stay.・The monthly rent includes utilities (water, gas, electricity), common area fees, tenant support, and multilingual support services.・The administrative fee includes a bedding set and Disinfection service.※In principle, no additional charges will be incurred other than those listed (except for optional services and utility usage exceeding our standard allowance).However, if utility usage significantly exceeds normal levels, or if any damage or soiling caused intentionally or negligently by the tenant is found at the time of move-out, additional charges may apply.※Please contact us separately if you would like to use additional options.※We will provide you with a quote based on the length of use.※In accordance with Ministry of Land, Infrastructure, Transport and Tourism guidelines, tenants are responsible for any fees incurred upon moving out.※For 2 people:In addition to utility fees, we charge  JPY 660  per day (tax included)  for each additional person.※Payment: Credit card (lump sum advance payment)",
  :vendor=>"Mynavi STAY",
  :vendor_image=>
  "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/umOgHp_rL8-1771388263269.png",
  :features=>["Elevator", "Free internet"],
  :all_amenities=>["Air conditioner", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
  ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/gLgMcwhwFn-1775614844737.jpg",
   "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/x-Rf5FnRQ8-1775108087944.png",
   "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Gj2YFAgmoQ-1775108086967.jpg",
   "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/6cPNFZEyQx-1775108087133.jpg",
   "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Kr9Mirzotf-1775108087281.jpg",
   "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/kIbLGpl9vs-1775108087438.jpg",
   "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/x4RV5hc1ZQ-1775108087729.jpg"],
  :stations=>["Meguro Sta. - 10 mins walk"]},

  {:name=>"SUMII Meguro Apt",
  :neighborhood=>"Meguro",
  :availability=>"Sep 11th",
  :latitude=>35.6351145,
  :longitude=>139.7128182,
  :price=>448200,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>40,
  :floors=>3,
  :description=>
    "*BRAND NEW* Stay at a brand new apartment at one of Tokyo’s most desirable neighborhoods. Staying near Meguro Station means effortless access to business hubs like Shibuya and Roppongi while enjoying a local vibe filled with trendy cafés, lush parks, and hidden izakayas.Seamless Connectivity – Just minutes from Meguro Station, giving you direct access to the Yamanote Line, Namboku Line, Mita Line, and Meguro Line.Trendy & Upscale – A mix of stylish cafés, boutique shops, and Michelin-starred restaurants.Riverside Charm – The Meguro river transforms with cherry blossoms in spring and stunning illuminations in winter.Laid-back Luxury – A perfect mix of urban energy and a peaceful residential vibe.*New* and fully furnished with the following amenities* FREE High-speed WIFI** Workspace in the room** Monthly Rentals Available*Landmarks- Meguro River Cherry Blossoms Promenade- Mark's Tokyo- Locale- Meguro Citizen Center Park- Meguro Museum of Art- Otori-jinja Shrine- Tonkatsu Tonki- Canoviano Cafe- Cafe Lounge Pandora- Tokyo Metropolitan Meien Art Museum",
  :rules=>
    "There are no other monthly fees. The only fees to secure the rental is an initial refundable deposit of 100,000Yen and an Exit Cleaning Fee of 20,000Yen. The total is 120,000Yen.Weekly cleaning is available, with a fee.",
  :vendor=>"SUMII Apartments",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/5i7bhrqOxN-1737511711192.jpg",
  :features=>["Balcony", "Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Free internet", "Free rent", "Furnished", "South facing"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/SA0T02Ms2O-1757995123199.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/HSHdBGPHgI-1742291225635.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Zku8jAHYe7-1742969298578.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/INoHUejrvd-1742969298677.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Wg-hnocaqx-1742291225557.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/JieFNa_65V-1742969298775.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Z8Vj-7ObTA-1742969298902.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/bI9hxGL4Tw-1742969298938.jpg"],
  :stations=>["Meguro Sta. - 5 mins walk"]},

  {:name=>"SUMII Nishi-Gotanda Apt",
  :neighborhood=>"Gotanda/Osaki",
  :availability=>"Sep 1st",
  :latitude=>35.6280825,
  :longitude=>139.7145389,
  :price=>575100,
  :layout=>"2LDK",
  :bedrooms=>2,
  :size=>53,
  :floors=>9,
  :description=>
    "SUMII offers thoughtfully and beautifully designed, fully furnished apartments in Tokyo. Each home is carefully curated with modern interiors and quality furnishings to provide a comfortable, seamless living experience from the moment you arrive.Located in Nishi-Gotanda in Shinagawa Ward, this apartment offers a comfortable balance between central Tokyo convenience and a relaxed residential atmosphere. The neighborhood is known for its mix of local restaurants, cafés, and everyday services, making daily life easy and enjoyable. With several train lines nearby, residents can reach many of Tokyo’s key districts quickly while still enjoying a quieter area to come home to.The apartment features modern interiors with a clean, functional layout designed for comfort and practicality. Whether you’re working remotely, studying, or unwinding after a busy day, the space offers a calm retreat from the lively city outside.With its unbeatable connectivity and welcoming neighborhood feel, SUMII Nishi-Gotanda is an ideal home base for experiencing Tokyo with ease, comfort, and character.Flexible staysNo key moneyNo agent commissions",
  :rules=>nil,
  :vendor=>"SUMII Apartments",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/5i7bhrqOxN-1737511711192.jpg",
  :features=>["Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Free internet", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Dishwasher", "Hair dryer", "Iron", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/15iw_A3TDI-1776242007769.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/_00k39KJFZ-1775532563608.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/bh4_gpBQZu-1776242008046.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ff29SyHLiL-1776242008215.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/wWR2_iHxvO-1776242008390.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/PyQAN64nYq-1776242008581.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/4DtYtPCu5Y-1776242008744.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lCpZN5lfSF-1776242008943.jpg"],
  :stations=>["Meguro Sta. - 11 mins walk", "Fudomae Sta. - 5 mins walk"]},

  {:name=>"MAISON MIYASHITA",
  :neighborhood=>"Gotanda/Osaki",
  :availability=>"now",
  :latitude=>35.6224538576,
  :longitude=>139.7195005116,
  :price=>336300,
  :layout=>"2LDK",
  :bedrooms=>2,
  :size=>69,
  :floors=>23,
  :description=>"・Maximum Number of Users：6 Person・Bed：Double Bed× 1、Semi-double bed x 2・Built in: November 1985",
  :rules=>
    "※This property has an android monitor instead of a TV.There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, prime video, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Bath & WS separated", "Free internet", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/SDU2cmNpYN-1745204199213.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/fkUVit2QCZ-1745204202926.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/-1_YgiOjbS-1745204214578.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/cNyM-uoDtP-1745204213332.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/drdnUSDPGJ-1745204215087.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/5ie_6-ebxU-1745204213583.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Giqqxa-Xt3-1745204213679.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/n57MGpNHQj-1745204217030.jpg"],
  :stations=>["Gotanda Sta. - 9 mins walk", "Fudomae Sta. - 11 mins walk", "Osaki-Hirokoji Sta. - 8 mins walk"]},

  {:name=>"La Sante Ikedayama 1202",
  :neighborhood=>"Gotanda/Osaki",
  :availability=>"June 25th",
  :latitude=>35.6281505,
  :longitude=>139.7222414,
  :price=>330000,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>54,
  :floors=>12,
  :description=>
    "Show up and start living.Building amenities unique to this one bedroom apartment include an on-site:ElevatorWashing machineThe entire apartment is yours to enjoy! You’ll either be personally greeted by a Blueground team member or given self check-in instructions.Throughout your stay, you’ll have access to our Client Experience team through the Blueground App. You can schedule additional cleanings, submit maintenance requests, and view our neighborhood recommendations with just a few taps.We’ll share all details upon confirmation of your stay.This Blueground apartment has flexible lease options, allowing you to book it for one month, a year, or more.We take great pride in ensuring every photo displayed is shot in our own units with our actual furnishings. That said, we regularly refresh our decor and furniture arrangement, which may differ from what’s pictured.",
  :rules=>
    "・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Bath & WS separated", "Delivery box", "Elevator", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=7s7GUxmRoF5",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/P220EU6rx0-1750770805941.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/N-iM_99KN2-1750770807172.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/XnUTF_oKtV-1750770806063.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/I6LGk7CnWF-1750770806151.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/U9VrKiTFiF-1750770806225.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Q2o-BSulOH-1750770806296.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/WlEFHepwxj-1750770806364.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/J4FxJrdzuk-1750770806443.png"],
  :stations=>["Meguro Sta. - 12 mins walk", "Gotanda Sta. - 3 mins walk", "Takanawadai Sta. - 14 mins walk"]},

  {:name=>"Dash Living Osaki - 303",
  :neighborhood=>"Shinagawa",
  :availability=>"Sep 25th",
  :latitude=>35.6170776,
  :longitude=>139.723033,
  :price=>325000,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>41,
  :floors=>3,
  :description=>
    "Osaki is a fantastic location on Tokyo’s most famous JR Yamanote, boasting commanding transportation options. Home to Sony headquarters along with a plethora of other corporates, Osaki has seen a redevelopment recently offering retail and commercial spots for all to enjoy. A major perk is the above ground sky walk which connects multiple shopping and retail outlets with Osaki Station. Perfect for joggers, Osaki also allows you to run next to the famous Meguo River, which during the spring time is considered one of the most beautiful Cherry Blossom viewing areas in the city. Our property is nestled in a quiet and quaint neighborhood that has beautiful cityscape views out the window that is sure to offer a comfortable and memorable stay.",
  :rules=>
    "1. Room availability is subject to real-time inventory constraints. Discounted rates apply only to designated room types and quantities.2. All promotional discounts are dynamically calculated based on: (i) booking date, and (ii) geographical location of the property.3. Offer cannot be used in conjunction with any other offer until availability is sold out.4. For details on the promotion terms, conditions, and availability, please contact us.5. Dash Living reserves the right to change the Terms and Conditions, and suspend or terminate the offers at any time without prior notice.6. Images are for illustration only, some of decorations shown might not be included in the actual room.7. Please contact sales for the latest price and details, as the price will vary depending on the contract period and conditions.",
  :vendor=>"Dash Living",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/S6TxBMTyBw-1765955575782.jpg",
  :features=>["Bath & WS separated", "Delivery box", "Elevator", "Free internet", "Furnished"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=bgD8LQQTJTs",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/yCR7DyX22_-1767064947093.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/3wgG3Q0gvU-1767064965552.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/kjNMHyxYKl-1767064947185.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/POZmNKnqYe-1767064947244.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aVcG2-ym-T-1767064947282.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/m9xkN1Ob4T-1767064947322.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/W3gt5kEnlT-1767064947368.jpg"],
  :stations=>["Osaki Sta. - 9 mins walk"]},

  {:name=>"Shibuya, Shoto  (3 months minimum) 702",
  :neighborhood=>"Shibuya",
  :availability=>"October 7th",
  :latitude=>35.656833,
  :longitude=>139.6927328,
  :price=>590000,
  :layout=>"2LDK",
  :bedrooms=>2,
  :size=>60,
  :floors=>0,
  :description=>
    "Modern Japanese Apartment in Prime Shibuya Location. This beautifully designed 2-bedroom, 1-bathroom apartment exemplifies contemporary Japanese living with its thoughtful layout and premium finishes. Located in the heart of Shibuya's sought-after Shinsencho district, this residence offers approximately 60m²  of meticulously planned living space.LAUNCHING SOON - Check-in Available from Early July 2025Interior Features:Open-concept living and dining room with abundant natural lightSpacious private balcony with city viewsBoth rooms feature ample closet space and clean, minimalist designSleek white cabinetry with integrated storage solutionsModern fixtures and finishes throughoutPeninsula-style counter perfect for casual diningSeparate laundry area with washer/dryer hookupsAdditional powder room for convenienceBuilding Amenities:Secure entry systemWell-maintained common areasProfessional building management / conciergeUnbeatable Shibuya Access:One of the most convenient locations for accessing Shibuya's business and entertainment districtsMultiple transportation options within walking distanceDirect connectivity to major JR and subway linesQuick access to Shibuya Crossing, shopping centers, and nightlifePeaceful Residential Haven:Located in quiet Shinsencho - near the action yet tranquilly removed from the crowdsTree-lined streets providing a serene atmosphereResidential neighborhood feel while maintaining urban conveniencePerfect escape from the bustling city centerClose proximity to shopping, dining, and entertainmentThe rare combination of central location with peaceful, quiet livingEasy access to parks and recreational facilitiesBest of both worlds: urban connectivity with residential tranquilityPerfect ForYoung professionals seeking modern urban living with easy Shibuya accessCouples looking for a stylish Tokyo residence in an ideal locationAnyone desiring the perfect balance of contemporary design and traditional Japanese aestheticsThose who want to be close to the excitement but value a quiet home environmentSample visualizations show furniture digitally designed for reference purposes.",
  :rules=>nil,
  :vendor=>"E-Housing",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/Mgy20jjSVl-1732084321369.jpg",
  :features=>["Balcony", "Bath & WS separated", "Elevator", "Floor heating", "Free internet", "Furnished", "Walk-in closet"],
  :all_amenities=>["Air conditioner", "Dishwasher", "Hair dryer", "Iron", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/_33HulpK_a-1749284421001.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/P4nf7NBZjd-1749284826551.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ynzC3LhlGB-1749284421098.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lISs4NqJGv-1749284421180.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/-pNp_6B9lV-1749284421242.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/5tu8s9bAUp-1749284421322.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/uxeqA2mvYK-1749284421385.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/eMXBAi6VYF-1749284421444.png"],
  :stations=>["Shibuya Sta. - 11 mins walk", "Shinsen Sta. - 5 mins walk"]},

  {:name=>"The Parkhabio Shibuya Cross #1103 3",
  :neighborhood=>"Shibuya",
  :availability=>"now",
  :latitude=>35.6534504,
  :longitude=>139.6934806,
  :price=>481000,
  :layout=>"2SLDK",
  :bedrooms=>2,
  :size=>66,
  :floors=>11,
  :description=>
    "Rental fees are subject to Dynamic Pricing. Contact us for more information.Rates vary depending on the duration of stay, season, and other parameters. For exact pricing, please visit our website and enter your desired move-in and move-out dates.Show up and start living from day one in Tokyo with this charming two bedroom Blueground apartment. You’ll love coming home to this thoughtfully furnished, beautifully designed, and fully-equipped Shibuya home with stunning balcony views over the city. (ID #TYO9)Designed with you in mindAs with any Blueground apartment, you’ll find a thoughtfully designed space complete with beautiful furniture and a fully-equipped kitchen in this two bedroom property. And, thanks to our superior quality mattresses, luxury linens, and towels, you can relax knowing you’ll always feel comfortably at home. When you’re ready for some fun, you can take in the Tokyo vibes or bring the entertainment to you with the premium wireless speaker or smart TV.Sleeping arrangementsQueen Bed, 63in/160cmDouble Bed, 55in/140cmAmenitiesBuilding amenities unique to this two bedroom apartment include an on-site:ElevatorWashing machineLoungeBuilding amenities may have an extra cost.This Blueground apartment has flexible lease options, allowing you to book it for one month, a year, or more.We take great pride in ensuring every photo displayed is shot in our own units with our actual furnishings. That said, we regularly refresh our decor and furniture arrangement, which may differ from what’s pictured.",
  :rules=>
    "・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Balcony", "Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Furnished", "Students allowed", "Walk-in closet"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=LqBLiy8U3HN",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/1sehHqdEj2-1748775191662.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/b5-3UZQRVL-1748775193260.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/nV6bMTeL6U-1748775191779.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Ez-pX6Rykz-1748775191842.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/02Y1bPgJjQ-1748775191982.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VzNu8n0s8c-1748775192050.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lNAwRIT04a-1748775192103.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/YHC0mf1jBo-1748775192185.png"],
  :stations=>["Shibuya Sta. - 10 mins walk"]},

  {:name=>"Shibuya Hill 301",
  :neighborhood=>"Shibuya",
  :availability=>"June 7th",
  :latitude=>35.6619707,
  :longitude=>139.703795,
  :price=>357900,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>40,
  :floors=>3,
  :description=>"Maximum Number of Users5 PersonBedSingle Bed(2)、Comforter(3)Age of Building8 Year(s)",
  :rules=>
    "■Towels and LinensPlease note that towels are provided for the number of guests regardless of the number of nights.※Linens and towels will not be changed during your stay.■Free Wi-Fi available※Please note that facilities and equipment are only provided upon initial installation and are not provided additionally.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Balcony", "Delivery box", "Elevator", "Furnished", "Students allowed", "Tower apartment"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "TV"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ytqoG0pmMR-1732864117172.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/TsujGZw3Ts-1732864118916.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/jNdBc0ZedC-1732864118380.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/jeI1yilA9E-1732864118859.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/S_UHgjh7Jh-1732864118458.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/2JuPvti435-1732864117657.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/i5C1YyPpsw-1732864118271.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/3WOlSOcW0c-1732864117807.jpg"],
  :stations=>["Shibuya Sta. - 7 mins walk", "Shinsen Sta. - 3 mins walk"]}
]

properties_data.each do |property_data|
  neighborhood = Neighborhood.find_by(name: property_data.delete(:neighborhood))
  Property.create!(property_data.merge(neighborhood: neighborhood))
end
