properties_data = [
  {:name=>"EstLargo Meguro - Studio 302",
  :neighborhood=>"Meguro",
  :latitude=>35.6311609,
  :longitude=>139.7107435,
  :price=>202000,
  :layout=>"1DK",
  :bedrooms=>1,
  :size=>24,
  :floors=>3,
  :description=>
    "Nestled a few minutes south of Meguro Station, this renovated property is well suited for someone looking to explore the area. Just beyond the city’s inner circle, Meguro District attracts commuters, families, and artists who appreciate subtle charms over sonorous environs. Despite its far-away residential feel, Meguro is not short of things to do. Cafes, famous izakaya, repurposed vintage shops, and must-see bookstores generate buzz that brings this area to life.",
  :rules=>
    "1. Room availability is subject to real-time inventory constraints. Discounted rates apply only to designated room types and quantities.2. All promotional discounts are dynamically calculated based on: (i) booking date, and (ii) geographical location of the property.3. Offer cannot be used in conjunction with any other offer until availability is sold out.4. For details on the promotion terms, conditions, and availability, please contact us.5. Dash Living reserves the right to change the Terms and Conditions, and suspend or terminate the offers at any time without prior notice.6. Images are for illustration only, some of decorations shown might not be included in the actual room.7. Subject to room type and availability. Please contact our specialist for further details.",
  :vendor=>"Dash Living",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/S6TxBMTyBw-1765955575782.jpg",
  :features=>["Elevator", "Free internet", "Furnished"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=gZYMM3kiJXe",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/puphRCu2B5-1766996461853.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/SUtju9s1bW-1766996461929.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/AAD7LKX5XA-1766996461971.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/dwknxki-9b-1766996462015.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/MUOT5R4NRK-1766996462053.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/t3Nf46yTLb-1766996462109.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Kos3995cj4-1766996462150.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9YN1vGHfRh-1766996462192.jpg"],
  :stations=>["Meguro Sta. - 8 min walk", "Fudomae Sta. - 8 min walk"]},

  {:name=>"The Parkhabio Meguro Place 2",
  :neighborhood=>"Meguro",
  :latitude=>35.6334663,
  :longitude=>139.712204,
  :price=>232000,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>34,
  :floors=>6,
  :description=>
    "Discover the best of Tokyo, with this one bedroom apartment in Shimomeguro. It’ll be easy to simply show up and start living in this beautifully Blueground furnished apartment with its fully equipped kitchen, bright living room, and our dedicated, on-the-ground support. (ID #TYO180)Rates vary depending on the duration of stay, season, and other parameters. For exact pricing, please visit our website and enter your desired move-in and move-out dates.• Gorgeous furniture• Fully equipped kitchen• Smart TV• Premium wireless speaker• Ideally located in Tokyo• Superior quality mattresses in every bedroom• Luxury linens and cozy towelsSleeping arrangementsDouble Bed, 55in/140cmAmenitiesBuilding amenities unique to this one bedroom apartment include an on-site:ElevatorWashing machine",
  :rules=>
    "・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Bath & WS separated", "Delivery box", "Elevator", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=gEnYRit6gTb",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/gnmfMHCDUa-1763646165327.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Geb8TvJhIG-1763646166193.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aOtzl1UtYx-1763646165432.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/7X6z2G-iZf-1763646165478.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/v6uIq30gq3-1763646165529.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/j2HAFd6jUk-1763646165573.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/3Sq-qJ9mXG-1763646165618.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/utSsKBJA2v-1763646165673.png"],
  :stations=>["Meguro Sta. - 5 min walk"]},

  {:name=>"Hmlet Nishi 405",
  :neighborhood=>"Shibuya",
  :latitude=>35.6563239,
  :longitude=>139.704141,
  :price=>292110,
  :layout=>"1LDK",
  :bedrooms=>1,
  :size=>33,
  :floors=>4,
  :description=>
    "【Fresh Start Special Discount】 Get ¥20,000 OFF your move-in costs!Kickstart your new life with Hmlet! We are excited to offer a special discount to help you settle in.Why not take this opportunity to experience the Hmlet lifestyle? A stylish living space and a convenient, comfortable lifestyle are waiting for you.＜Campaign Details＞Offer: ¥20,000 OFF your initial move-in costs＜Terms & Conditions＞Move-in Period: Applicable for residents starting their stay between May 1 and June 30, 2026Eligible Properties: All Hmlet propertiesEligibility: This campaign is available exclusively to first-time residents who sign a new lease. Please note that current residents who are extending their existing contracts, as well as former residents returning through a re-contract or relocating/transferring between Hmlet properties, are not eligible for this discount.＜How to Apply＞When applying, please mention that you saw the campaign.Located just a 4-minute walk from Nishi-shinjuku-gochome Station on the Toei Oedo Line, and a convenient 10-minute stroll to Nakano-sakaue Station on the Tokyo Metro Marunouchi Line, Hmlet Nishi-Shinjuku offers unmatched accessibility in the heart of Tokyo. With a quick 4-minute direct connection to Shinjuku Station, it ensures you have everything you need for daily living right at your fingertips, eliminating any shopping concerns. While Shinjuku's main streets buzz with office buildings and vibrant activity, Nishi-shinjuku offers a tranquil retreat just off the beaten path, providing a peaceful atmosphere amidst the city's hustle and bustle.Explore the expansive Shinjuku Chuo Park, located within walking distance, or indulge in the amenities of SHUKNOVA, a facility featuring restaurants and a fitness club. Experience the beauty of nature throughout the seasons, from lush greenery to cherry blossom viewing during springtime, making it a popular destination for tourists from around the world. Why not embrace the convenience and cosmopolitan lifestyle of Hmlet Nishi-Shinjuku? Your urban adventure awaits!",
  :rules=>
    "＊Move-in Fees (One-time Payment, applicable to all contracts.)Service Fee(Non-refundable): 10% of Rent SubtotalMove Out Cleaning Fee: 25% of List Price＊Optional Fees (If Applicable)Pet Fee: ¥110,000 (Non-refundable)Bicycle Parking Registration Fee: ¥3,300 (One-time payment per bicycle)Rental Futon Set: ¥22,000 (One-time payment per set)＊Included in Service Fee:- Utilities & Internet Fees- Customer Support & Emergency Call Center- No Brokerage Fee- No Key Money Required＊Kitchen Essentials Provided:- Cooking utensils and cutlery are included in the room.https://drive.google.com/file/d/1sSyG7K30TXeBjV3xSmGH7E2I8Xqu1zRB/view",
  :vendor=>"Hmlet Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/nQuMexfOpn-1725438035620.jpg",
  :features=>["Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Free internet", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=FfgtwARdmJp",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/pYkPqma_5P-1774321148868.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/GESIbsXLTS-1750069392003.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/RaeZ6wBJHF-1774321171084.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/p5V31oWbEa-1774321133150.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/yUejNWxOxr-1774321133388.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/iV-VPYnFR4-1774321133574.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/XPIHyyA-Fx-1774321108968.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lDPFTQRIe5-1774321109193.jpg"],
  :stations=>["Nakano-sakaue Sta. - 10 min walk", "Nishi-shinjuku-gochome Sta. - 4 min walk", "Tochōmae Sta. - 12 min walk"]},

  {:name=>"Palace Studio 207",
  :neighborhood=>"Meguro",
  :latitude=>35.6414529,
  :longitude=>139.6980773,
  :price=>185400,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>23,
  :floors=>2,
  :description=>"Maximum Number of Users2 PersonBedDouble Bed(1)Age of Building19 Year(s)",
  :rules=>
    "※This propaty has free wi-fi.※This property has an android monitor instead of a TV.　There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, Amazon Prime, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Delivery box", "Elevator", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/eTJ8e65Kv_-1732266075484.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VHreBPb3g--1732266076446.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/sTz0wpUMLw-1732266076401.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/1Xij6JAQpg-1732266075699.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ruhTOp_SL5-1732266076146.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/q09qM_zPua-1732266077555.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/d5_Ei0z3aW-1732266077850.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/PztYKWsqL--1732266076218.jpg"],
  :stations=>["Shibuya Sta. - 12 min walk", "Ikejiri-Ohashi Sta. - 11 min walk", "Shinsen Sta. - 7 min walk"]},

  {:name=>"The Apartment Hotel Ebisu 1 Large typeA 102",
  :neighborhood=>"Ebisu",
  :latitude=>35.6492576,
  :longitude=>139.717365,
  :price=>290000,
  :layout=>"1DK",
  :bedrooms=>1,
  :size=>41,
  :floors=>15,
  :description=>
    "Contrasting the glamorous station-side area, Ebisu’s back streets are lined with shops for those with a discerning eye. The area’s bars are another drawcard, with almost too many renowned establishments to choose from.＊Applianceswashing machine,refrigerator,microwave,electric kettle,coffee dripper,IH stove,tableware,cutlery,pot,frying pan,kitchen knife,cutting board＊Amenities bath amenities, towels, toothbrush, hairbrush(Refills during your stay are not available)Double bed x 1.  Please contact us if you would like to bring your child.",
  :rules=>
    "2026-08-20 ~ 2026-10-01 is available2026-12-01 ~ 2027-03-01 is available＊A guarantor company is required.＊Initial fees consist of:・First month's prorated rent (next month’s rent may be included depending on timing)・Initial fee (10% of monthly rent)・Cleaning fee (20% of monthly rent)",
  :vendor=>"The Apartment Hotel",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/QDKWgNZwef-1753255036160.jpg",
  :features=>["Balcony", "Delivery box", "Elevator", "Free internet", "Furnished"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://r15601879.theta360.biz/t/3a931ef0-bb02-11f0-b72e-0ad00fde431f-1",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/zg0cyhPK2E-1755239851972.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/hy_gnj7Jw3-1755239852416.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/grrACNjOLS-1755239852054.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/8rWwxluhS_-1755239852093.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/2wGVxOYYjR-1755239852133.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aRHSIns3gD-1755239852172.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/QIY3RpMkG0-1755239852208.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/fiFl9JofSa-1755239852248.jpg"],
  :stations=>["Ebisu Sta. - 10 min walk", "Hiroo Sta. - 8 min walk"]},

  {:name=>"Hmlet Shibuyaohashi【Spring Special Offer】 203",
  :neighborhood=>"Meguro",
  :latitude=>35.6551771,
  :longitude=>139.6889239,
  :price=>186180,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>18,
  :floors=>2,
  :description=>
    "【Fresh Start Special Discount】 Get ¥20,000 OFF your move-in costs!Kickstart your new life with Hmlet! We are excited to offer a special discount to help you settle in.Why not take this opportunity to experience the Hmlet lifestyle? A stylish living space and a convenient, comfortable lifestyle are waiting for you.＜Campaign Details＞Offer: ¥20,000 OFF your initial move-in costs＜Terms & Conditions＞Move-in Period: Applicable for residents starting their stay between May 1 and June 30, 2026Eligible Properties: All Hmlet propertiesEligibility: This campaign is available exclusively to first-time residents who sign a new lease. Please note that current residents who are extending their existing contracts, as well as former residents returning through a re-contract or relocating/transferring between Hmlet properties, are not eligible for this discount.＜How to Apply＞When applying, please mention that you saw the campaign.Hmlet Shibuya Ohashi: The Perfect Balance of Urban Convenience and Natural Serenity Located within walking distance of Shibuya Station, Hmlet Shibuya Ohashi offers a unique blend of city vibrancy and natural tranquility. With excellent accessibility—just an 8-minute walk from Keio Inokashira Line’s Shinsen Station and a 9-minute walk from Tokyu Den-en-toshi Line’s Ikejiri-Ohashi Station—you can reach Shibuya Station in just 2 minutes. Major hubs like Shinjuku and Shinagawa are also just one transfer away. Additionally, a limousine bus from Shibuya Fukuras provides a direct connection to Haneda Airport in approximately 40 minutes. The property is also conveniently located near the University of Tokyo’s Komaba Campus, making it ideal for students. The surrounding area features 24-hour supermarkets such as Maruetsu and Seijo Ishii, ensuring hassle-free daily shopping. Enjoy the seasonal beauty of cherry blossoms along the Meguro River Greenway, relax at Meguro Sky Garden, or explore Setagaya Park and Komabano Park, perfect for outdoor activities like walking and BBQs. The neighborhood is also dotted with charming cafés, specialty restaurants, and boutique shops, offering plenty of options for leisure and entertainment. Experience a lifestyle where urban convenience meets natural tranquility at Hmlet Shibuya Ohashi. Why not start your next chapter here?",
  :rules=>
    "＊Move-in Fees (One-time Payment, applicable to all contracts.)Service Fee(Non-refundable): 10% of Rent SubtotalMove Out Cleaning Fee: 25% of List Price＊Optional Fees (If Applicable)Pet Fee: ¥110,000 (Non-refundable)Bicycle Parking Registration Fee: ¥3,300 (One-time payment per bicycle)Rental Futon Set: ¥22,000 (One-time payment per set)＊Included in Service Fee:- Utilities & Internet Fees- Customer Support & Emergency Call Center- No Brokerage Fee- No Key Money Required＊Kitchen Essentials Provided:- Cooking utensils and cutlery are included in the room.https://drive.google.com/file/d/1sSyG7K30TXeBjV3xSmGH7E2I8Xqu1zRB/view",
  :vendor=>"Hmlet Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/nQuMexfOpn-1725438035620.jpg",
  :features=>["Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Free internet", "Furnished", "Pet allowed", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=rexoCpMXyxV&ts=1",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/zIEMHV949p-1749629748414.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/oKAHV4ZAvv-1749629573689.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/PMZBHhiURc-1749629748512.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/M9Tjseys2_-1749629748546.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/t4W_cYcmPO-1749629748589.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/KA7uN4gRlv-1749629748712.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/qM441kSDsd-1749629748769.jpg"],
  :stations=>["Shinsen Sta. - 8 min walk"]},

  {:name=>"The Apartment Hotel Shibuya 701",
  :neighborhood=>"Shibuya",
  :latitude=>35.6540092,
  :longitude=>139.6998735,
  :price=>336000,
  :layout=>"Studio",
  :bedrooms=>0,
  :size=>41,
  :floors=>77,
  :description=>
    "Daikanyama is home to high-quality shops and restaurants with a relaxed atmosphere, away from the hustle and bustle of Shibuya. Starting at Daikanyama T-Site, a cultural symbol, Nakameguro and Ebisu are located just a short walk away, making the area perfect for a stroll on a sunny day.＊Applianceswashing machine,refrigerator,microwave,electric kettle,coffee dripper,IH stove,tableware,cutlery,pot,frying pan,kitchen knife,cutting board＊Amenities bath amenities, towels, toothbrush, hairbrush(Refills during your stay are not available)Double bed x 2 　Please contact us if you would like to bring your child.",
  :rules=>
    "2026-07-31~ 2026-09-30 is available2026-12-01 ~ 2027-03-02 is available＊A guarantor company is required.＊Initial fees consist of:・First month's prorated rent (next month’s rent may be included depending on timing)・Initial fee (10% of monthly rent)・Cleaning fee (20% of monthly rent)",
  :vendor=>"The Apartment Hotel",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/QDKWgNZwef-1753255036160.jpg",
  :features=>["Balcony", "Bath & WS separated", "Delivery box", "Elevator", "Free internet", "Furnished"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>"https://r15601879.theta360.biz/t/19064d2c-ab42-11f0-b248-0613720b7bf9-1",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Sj4G1U_eFb-1755241574397.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/CWT4UQi6S6-1755242415907.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/uBTLhAaiO7-1755241574550.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ZRv379Nf8q-1755241574477.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/lf-YnmSw7u-1755241574510.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/EKKzrFXgeI-1755241574583.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/aIQk7LQk3U-1755241574623.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ihB28ahbdU-1755241574659.jpg"],
  :stations=>["Shibuya Sta. - 6 min walk", "Daikanyama Sta. - 12 min walk"]},

  {:name=>"The Parkhabio Cross #1004 2",
  :neighborhood=>"Meguro",
  :latitude=>35.6534504,
  :longitude=>139.6934806,
  :price=>337000,
  :layout=>"1SLDK",
  :bedrooms=>1,
  :size=>57,
  :floors=>10,
  :description=>
    "Rental fees are subject to Dynamic Pricing. Contact us for more information.Rates vary depending on the duration of stay, season, and other parameters. For exact pricing, please visit our website and enter your desired move-in and move-out dates.Show up and start living from day one in Tokyo with this comfortable one bedroom Blueground apartment. You’ll love coming home to this thoughtfully furnished, beautifully designed, and fully-equipped Shibuya home with stunning balcony views over the city. (ID #TYO8)Designed with you in mindAs with any Blueground apartment, you’ll find a thoughtfully designed space complete with beautiful furniture and a fully-equipped kitchen in this one bedroom property. And, thanks to our superior quality mattresses, luxury linens, and towels, you can relax knowing you’ll always feel comfortably at home. When you’re ready for some fun, you can take in the Tokyo vibes or bring the entertainment to you with the premium wireless speaker or smart TV.Sleeping arrangementsQueen Bed, 63in/160cmAmenitiesBuilding amenities unique to this one bedroom apartment include an on-site:ElevatorWashing machineLoungeBuilding amenities may have an extra cost.This Blueground apartment has flexible lease options, allowing you to book it for one month, a year, or more.We take great pride in ensuring every photo displayed is shot in our own units with our actual furnishings. That said, we regularly refresh our decor and furniture arrangement, which may differ from what’s pictured.",
  :rules=>
    "・One-time booking fee required・1-month refundable deposit・Rent varies by stay duration, season, etc. (dynamic pricing)・For exact rates, please check our website or contact us",
  :vendor=>"Blueground Japan",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/WOlgSDyPjI-1728616304184.png",
  :features=>["Balcony", "Bath & WS separated", "Bicycle parking", "Delivery box", "Elevator", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Iron", "LAN ethernet socket", "Microwave", "Refrigerator", "TV", "Washing machine"],
  :matterport_url=>"https://my.matterport.com/show/?m=PunYXwWCgkZ",
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9VR65mjUli-1748771243462.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/9jDOrhhCMy-1748771244854.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Fp6kCBDeCH-1748771243554.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/w3PqpbfRsG-1748771243625.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/uYDO8gNnbV-1748771243710.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/cMzgMEBHkR-1748771243849.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/hCfKYZK604-1748771243967.png",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/jbGpOyWA9L-1748771244051.png"],
  :stations=>["Shibuya Sta. - 10 min walk"]},

  {:name=>"T.S. Heim 201 201",
  :neighborhood=>"Shibuya",
  :latitude=>35.6451241144,
  :longitude=>139.7132500994,
  :price=>168600,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>14,
  :floors=>2,
  :description=>"・Maximum Number of Users：1 Person・Bed：Shingle x 1・Built in: December 1990",
  :rules=>
    "※This property has an android monitor instead of a TV.There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, prime video, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Bath & WS separated", "Free internet", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/0bO3oNwiS9-1745209958170.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/TJ2J_QMAsi-1745209958286.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/tnjOQ5471F-1745209968176.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/Bsyvho62_F-1745209968248.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/GzWxYUVEP3-1745209968553.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VBLyRoSPpm-1745209969700.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/7cwBe-Xl1X-1745209968082.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/e0-qvfFd14-1745209968636.jpg"],
  :stations=>["Ebisu Sta. - 5 min walk", "Hiroo Sta. - 17 min walk", "Daikanyama Sta. - 15 min walk"]},

  {:name=>"Oak Rest Ebisu 503 503",
  :neighborhood=>"Ebisu",
  :latitude=>35.6445351,
  :longitude=>139.7210448,
  :price=>185400,
  :layout=>"Studio",
  :bedrooms=>1,
  :size=>20,
  :floors=>5,
  :description=>"Maximum Number of Users：2 PersonBed：Double Bed(1)Age of Building：4 Year(s)",
  :rules=>
    "※This propaty has free wi-fi.※This property has an android monitor instead of a TV.　There is no TV tuner installed in the apartment, so you will not be able to watch terrestrial TV.You can watch Netflix, Amazon Prime, etc. with your own account, or you can watch Youtube, etc. for free.",
  :vendor=>"Sumyca",
  :vendor_image=>
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/companies/bjHqg1Wmiq-1729067302615.png",
  :features=>["Bath & WS separated", "Furnished", "Students allowed"],
  :all_amenities=>["Air conditioner", "Hair dryer", "Microwave", "Refrigerator", "Washing machine"],
  :matterport_url=>nil,
  :images=>
    ["https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/ynjWrsGB_p-1739868727650.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/98CB0tjk8s-1739868729425.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/r-Oa5VtOSD-1739868727726.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/VxQV85zw7Z-1739868727760.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/okJkIjUGXd-1739868727801.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/LqByqUhT3f-1739868727840.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/MKndITS1sV-1739868727892.jpg",
    "https://cdn.shortpixel.ai/client/to_webp,w_1500,q_lossless,ret_wait/https://ehousing-dev.s3.ap-northeast-1.amazonaws.com/properties/6o4QkvJk4m-1739868727945.jpg"],
  :stations=>["Shirokanedai Sta. - 14 min walk", "Ebisu Sta. - 13 min walk", "Hiroo Sta. - 10 min walk"]}
]

properties_data.each do |property_data|
  neighborhood = Neighborhood.find_by(name: property_data.delete(:neighborhood))
  Property.create!(property_data.merge(neighborhood: neighborhood))
end
